# Generated by Django 2.2.4 on 2023-10-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp89', '0002_auto_20231016_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': '获奖和荣誉', 'verbose_name_plural': '获奖和荣誉'},
        ),
    ]
