# Generated by Django 2.2.4 on 2023-10-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp89', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报'),
        ),
    ]
